Frontend/schedule page
KnightHacks/hackathon-site-2021 pull request #88
Opened 2021-04-28 19:11 UTC by aileenpongnon

###### ISSUE

Resolves #47.

###### DESCRIPTION

renders Schedule page with data populated from JSON. includes colored tags from schedule's legend using [color-hash](https://www.npmjs.com/package/color-hash) library

###### CHECKLIST

✓ Code is commented

✓ Responsiveness across viewports

✓ Labeled "frontend"

2021-05-13 18:40 UTC, rob-3 approved these changes

2021-05-13 18:42 UTC, rob-3 requested changes
I do get a warning for not using a key prop in a list that should be fixed before this is merged.

2021-05-13 18:46 UTC, rob-3 requested changes

2021-05-13 18:46 UTC, rob-3 commented on frontend/src/pages/Schedule.js
> +              {event.events.map(function (item, index) {
You can use an arrow function here

2021-05-13 18:46 UTC, rob-3 commented on frontend/src/pages/Schedule.js
> +                  <div className="mb-5">
You should use a `key` prop here.

2021-05-13 18:46 UTC, rob-3 commented on frontend/src/pages/Schedule.js
> +                      <span
You should use a `key` prop here

2021-05-13 18:46 UTC, rob-3 commented on frontend/src/pages/Schedule.js
> +  const hash = new ColorHash({ lightness: 0.8 });
Performance will be slightly better if you lift this out of the component; otherwise it will reinitialize on every render.

2021-06-05 20:50 UTC, aileenpongnon commented
> I do get a warning for not using a key prop in a list that should be fixed before this is merged.

I'm trying to reproduce this but I'm not getting this same warning? I'll go ahead and include the prop though

2021-06-05 20:54 UTC, rob-3 commented
> > I do get a warning for not using a key prop in a list that should be fixed before this is merged.
> 
> I'm trying to reproduce this but I'm not getting this same warning? I'll go ahead and include the prop though

Have you checked the browser log?

2021-06-05 20:55 UTC, aileenpongnon commented
> > > I do get a warning for not using a key prop in a list that should be fixed before this is merged.
> > 
> > 
> > I'm trying to reproduce this but I'm not getting this same warning? I'll go ahead and include the prop though
> 
> Have you checked the browser log?

good point, I see it now

2021-06-05 22:48 UTC, rob-3 requested changes

2021-06-05 22:48 UTC, rob-3 commented on frontend/src/pages/Schedule.js
> +        {content.map((event) => {
Key prop here as well

2021-06-06 15:57 UTC, rob-3 commented
Looks good; approved!

2021-06-06 15:57 UTC, rob-3 approved these changes

2021-06-06 16:47 UTC, merged